"""CP-016/017/018 — exclusion rules for the code packer.

Three filters compose into one `is_excluded(path)` predicate:

1. ``.gitignore`` patterns.
2. ``.ctxpackignore`` overlay (same syntax).
3. Built-in heuristics for the common generated-code patterns we want
   skipped by default (``__pycache__``, ``*_pb2.py``, Alembic
   migrations, generated ``.d.ts``, build outputs).

No external dependency — we implement gitignore-style matching with
``fnmatch`` over forward-slash paths relative to the repo root.
"""

from __future__ import annotations

from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path
from typing import Iterator


_GENERATED_MARKERS = ("code generated by", "do not edit")
_GENERATED_PROBE_BYTES = 200


# Hard-coded heuristic rules — built-in, not overrideable in v0. These
# are the patterns where the cost of indexing them dwarfs any
# conceivable value. Users can opt back in by adding a negation rule
# to ``.ctxpackignore`` (`!some_pattern`) in a future iteration.
_HEURISTIC_PATTERNS = [
    "**/__pycache__/**",
    "**/*.pyc",
    "**/*_pb2.py",
    "**/*_pb2_grpc.py",
    "**/migrations/versions/*.py",
    "**/.next/**",
    "**/dist/**",
    "**/build/**",
    "**/node_modules/**",
    "**/.venv/**",
    "**/venv/**",
    "**/.git/**",
]


@dataclass(frozen=True)
class ExclusionRules:
    """Parsed exclusion patterns. Heuristics are not stored here —
    they're applied unconditionally by ``is_excluded``.
    """

    gitignore_patterns: list[str]
    ctxpackignore_patterns: list[str]


def load_exclusion_rules(root: Path) -> ExclusionRules:
    """Read ``.gitignore`` and ``.ctxpackignore`` from ``root``.

    Missing files yield empty pattern lists — not an error. Patterns
    are normalised: comments (``#...``) and blank lines dropped;
    leading/trailing whitespace trimmed.
    """
    return ExclusionRules(
        gitignore_patterns=_read_ignore(root / ".gitignore"),
        ctxpackignore_patterns=_read_ignore(root / ".ctxpackignore"),
    )


def is_excluded(
    path: Path, *, root: Path, rules: ExclusionRules
) -> bool:
    """Return True if ``path`` (file or directory) should be skipped."""
    try:
        rel = path.resolve().relative_to(root.resolve())
    except ValueError:
        return False
    rel_str = str(rel).replace("\\", "/")

    # Heuristics first — cheapest checks, no I/O.
    for pat in _HEURISTIC_PATTERNS:
        if _matches(rel_str, pat):
            return True

    # User-supplied .gitignore / .ctxpackignore patterns.
    for pat in rules.gitignore_patterns + rules.ctxpackignore_patterns:
        if _matches(rel_str, pat):
            return True

    # Generated-code marker for .d.ts files (cheap content sniff).
    if path.is_file() and path.suffix == ".ts" and path.name.endswith(".d.ts"):
        if _has_generated_marker(path):
            return True

    return False


def iter_python_files(root: Path) -> Iterator[Path]:
    """Walk ``root``, yielding ``.py`` files that pass all exclusion
    filters.

    Yields in deterministic order (sorted by path) so two iterations of
    the same tree produce the same sequence — needed by the §8.6
    determinism CI gate later.
    """
    rules = load_exclusion_rules(root)
    for p in sorted(root.rglob("*.py")):
        if is_excluded(p, root=root, rules=rules):
            continue
        yield p


def _read_ignore(path: Path) -> list[str]:
    if not path.is_file():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        out.append(line)
    return out


def _matches(rel_path: str, pattern: str) -> bool:
    """Match ``rel_path`` (forward-slash, relative to root) against a
    gitignore-style pattern.

    Handles three common shapes:
    - ``foo`` — matches that name anywhere in the tree (any depth).
    - ``foo/`` — matches the directory ``foo`` and anything under it.
    - ``a/b/c`` — anchored path match.
    - ``**/x/**`` — any-depth glob.
    """
    # Directory-only pattern (`foo/`) is shorthand for "this dir and
    # everything beneath it." Convert to ``foo`` + ``foo/**``.
    base_patterns: list[str] = []
    if pattern.endswith("/"):
        base = pattern.rstrip("/")
        base_patterns.append(base)
        base_patterns.append(f"{base}/**")
        # also match deeper occurrences
        base_patterns.append(f"**/{base}")
        base_patterns.append(f"**/{base}/**")
    elif "/" not in pattern:
        # Bare name → match at any depth.
        base_patterns.append(pattern)
        base_patterns.append(f"**/{pattern}")
        base_patterns.append(f"{pattern}/**")
        base_patterns.append(f"**/{pattern}/**")
    else:
        base_patterns.append(pattern)
        # Also try as a directory prefix.
        if not pattern.endswith("**"):
            base_patterns.append(f"{pattern}/**")
    for p in base_patterns:
        if _fnmatch_with_double_star(rel_path, p):
            return True
    return False


def _fnmatch_with_double_star(path: str, pattern: str) -> bool:
    """`fnmatch` doesn't natively understand `**`. Translate it.

    Treats ``**`` as "any path segment, any depth (including empty)".
    """
    # Convert ** segments to a marker that fnmatch handles via *
    # over slashes too — easiest is to fnmatch over the full path
    # treating '/' as just another char.
    if pattern == "**":
        return True
    # Replace ** with a placeholder that matches any number of chars
    # INCLUDING slashes.
    if "**" in pattern:
        # fnmatch's * does not cross / by convention but in our
        # implementation we want it to — that's exactly what ** means.
        regex_pat = _glob_to_regex(pattern)
        import re
        return re.fullmatch(regex_pat, path) is not None
    # Single-star pattern: use fnmatch with normalised slashes.
    return fnmatch(path, pattern)


def _glob_to_regex(pattern: str) -> str:
    """Translate a gitignore-style glob with ``**`` into a regex.

    Rules:
    - ``**`` → ``.*`` (matches any chars including slashes)
    - ``*`` → ``[^/]*`` (any chars except slash)
    - ``?`` → ``[^/]`` (single non-slash char)
    - other regex specials → escaped
    """
    import re
    out = []
    i = 0
    while i < len(pattern):
        c = pattern[i]
        if c == "*":
            if i + 1 < len(pattern) and pattern[i + 1] == "*":
                out.append(".*")
                i += 2
                # Skip following slash so `**/x` matches `x` too.
                if i < len(pattern) and pattern[i] == "/":
                    i += 1
                continue
            out.append("[^/]*")
            i += 1
            continue
        if c == "?":
            out.append("[^/]")
            i += 1
            continue
        if c in ".+()|^$[]{}\\":
            out.append("\\" + c)
            i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


def _has_generated_marker(path: Path) -> bool:
    """Sniff the first ~200 bytes for a "Code generated by" /
    "DO NOT EDIT" marker (case-insensitive).
    """
    try:
        with path.open("rb") as f:
            head = f.read(_GENERATED_PROBE_BYTES)
    except OSError:
        return False
    decoded = head.decode("utf-8", errors="ignore").lower()
    return any(m in decoded for m in _GENERATED_MARKERS)
