#!/usr/bin/env python3
"""Post-write quality check — standalone, stdlib only.

Auto-generated by the codebase harness generator.
Checks files after every write for common quality issues.

Exit codes: 0 = pass, 1 = warnings found (printed to stderr).
"""

import ast
import os
import sys

# --- Configuration (detected from codebase) ---
TEST_DIRS = ['tests']
UTIL_DIRS = ['ctxpack/core']
MAX_FILE_LINES = 500


def check_python_file(filepath: str) -> list[str]:
    """Check a Python file for quality issues."""
    warnings: list[str] = []

    try:
        with open(filepath, encoding="utf-8", errors="replace") as f:
            source = f.read()
    except OSError:
        return warnings

    lines = source.split("\n")

    # Check file length
    if len(lines) > MAX_FILE_LINES:
        warnings.append(
            f"{filepath}: {len(lines)} lines (max {MAX_FILE_LINES}) — consider splitting"
        )

    # Parse AST for deeper checks
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return warnings

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # Skip private/test functions
            if node.name.startswith("_") or node.name.startswith("test_"):
                continue

            # Check return type annotation on public functions
            if node.returns is None:
                warnings.append(
                    f"{filepath}:{node.lineno}: public function `{node.name}` "
                    f"missing return type annotation"
                )

            # Check route handlers for return type
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute):
                    method = dec.func.attr
                    if method in ("get", "post", "put", "delete", "patch"):
                        if node.returns is None:
                            warnings.append(
                                f"{filepath}:{node.lineno}: route handler "
                                f"`{node.name}` missing return type"
                            )

    return warnings


def check_missing_test(filepath: str) -> list[str]:
    """Check if a new source file has a corresponding test file."""
    warnings: list[str] = []

    # Only check Python source files (not tests themselves)
    if not filepath.endswith(".py"):
        return warnings

    basename = os.path.basename(filepath)
    if basename.startswith("test_") or basename.startswith("conftest"):
        return warnings

    # Skip __init__.py and migration files
    if basename == "__init__.py" or "alembic" in filepath or "migration" in filepath:
        return warnings

    # Look for corresponding test file
    name_stem = basename.replace(".py", "")
    expected_test = f"test_{name_stem}.py"

    # Search in known test dirs
    found = False
    for test_dir in TEST_DIRS:
        for dirpath, _, filenames in os.walk(test_dir):
            if expected_test in filenames:
                found = True
                break
        if found:
            break

    if not found and TEST_DIRS:
        warnings.append(
            f"{filepath}: no test file `{expected_test}` found in {TEST_DIRS}"
        )

    return warnings


def check_local_utility_reimport(filepath: str) -> list[str]:
    """Check if file imports something that already exists in utils/lib."""
    warnings: list[str] = []
    if not filepath.endswith(".py"):
        return warnings

    try:
        with open(filepath, encoding="utf-8", errors="replace") as f:
            source = f.read()
        tree = ast.parse(source)
    except (OSError, SyntaxError):
        return warnings

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for util_dir in UTIL_DIRS:
                norm = util_dir.replace("/", ".").replace("\\", ".")
                if norm and norm in node.module:
                    # This is fine — they ARE using the local utility
                    break
    return warnings


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: quality-check.py <filepath>", file=sys.stderr)
        return 0

    filepath = sys.argv[1]
    if not os.path.isfile(filepath):
        return 0

    all_warnings: list[str] = []

    if filepath.endswith(".py"):
        all_warnings.extend(check_python_file(filepath))
        all_warnings.extend(check_missing_test(filepath))
        all_warnings.extend(check_local_utility_reimport(filepath))
    elif filepath.endswith((".ts", ".tsx")):
        # Basic line count check for TS files
        try:
            with open(filepath, encoding="utf-8", errors="replace") as f:
                line_count = sum(1 for _ in f)
            if line_count > MAX_FILE_LINES:
                all_warnings.append(
                    f"{filepath}: {line_count} lines (max {MAX_FILE_LINES}) — consider splitting"
                )
        except OSError:
            pass

    if all_warnings:
        for w in all_warnings:
            print(f"WARN: {w}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
