"""CP-016/017/018 — exclusion rules: gitignore, ctxpackignore, heuristics."""

from __future__ import annotations

from pathlib import Path

import pytest


class TestGitignore:
    def test_gitignored_path_excluded(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / ".gitignore").write_text("secrets.py\n*.log\n")
        (tmp_path / "secrets.py").write_text("API_KEY=1\n")
        (tmp_path / "ok.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(tmp_path / "secrets.py", root=tmp_path, rules=rules)
        assert not is_excluded(tmp_path / "ok.py", root=tmp_path, rules=rules)

    def test_glob_pattern(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / ".gitignore").write_text("logs/\n")
        (tmp_path / "logs").mkdir()
        (tmp_path / "logs" / "x.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(tmp_path / "logs" / "x.py", root=tmp_path, rules=rules)

    def test_double_star_glob(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / ".gitignore").write_text("**/generated/*.py\n")
        (tmp_path / "a" / "generated").mkdir(parents=True)
        (tmp_path / "a" / "generated" / "x.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(
            tmp_path / "a" / "generated" / "x.py",
            root=tmp_path, rules=rules,
        )


class TestCtxpackignore:
    def test_overlay_respected(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / ".gitignore").write_text("# empty\n")
        (tmp_path / ".ctxpackignore").write_text("ephemeral/\n")
        (tmp_path / "ephemeral").mkdir()
        (tmp_path / "ephemeral" / "a.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(tmp_path / "ephemeral" / "a.py", root=tmp_path, rules=rules)


class TestHeuristics:
    def test_pycache_dropped(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / "__pycache__").mkdir()
        (tmp_path / "__pycache__" / "x.cpython-313.pyc").write_text("noop")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(
            tmp_path / "__pycache__" / "x.cpython-313.pyc",
            root=tmp_path, rules=rules,
        )

    def test_pb2_dropped(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / "models_pb2.py").write_text("x = 1\n")
        (tmp_path / "models_pb2_grpc.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(tmp_path / "models_pb2.py", root=tmp_path, rules=rules)
        assert is_excluded(
            tmp_path / "models_pb2_grpc.py", root=tmp_path, rules=rules,
        )

    def test_alembic_migrations_dropped(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        (tmp_path / "migrations" / "versions").mkdir(parents=True)
        f = tmp_path / "migrations" / "versions" / "abc123_init.py"
        f.write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(f, root=tmp_path, rules=rules)

    def test_dts_with_generated_marker_dropped(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        f = tmp_path / "schema.d.ts"
        f.write_text("// Code generated by codegen. DO NOT EDIT.\nexport type X = number;\n")
        rules = load_exclusion_rules(tmp_path)
        assert is_excluded(f, root=tmp_path, rules=rules)

    def test_dts_user_written_retained(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        f = tmp_path / "my_types.d.ts"
        f.write_text("export interface User { id: number; name: string; }\n")
        rules = load_exclusion_rules(tmp_path)
        assert not is_excluded(f, root=tmp_path, rules=rules)

    def test_build_outputs_dropped(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules, is_excluded
        for d in ("dist", "build", ".next"):
            (tmp_path / d).mkdir()
            (tmp_path / d / "x.py").write_text("x = 1\n")
        rules = load_exclusion_rules(tmp_path)
        for d in ("dist", "build", ".next"):
            assert is_excluded(tmp_path / d / "x.py", root=tmp_path, rules=rules), d


class TestIterPythonFiles:
    def test_walks_only_passing_files(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import iter_python_files
        (tmp_path / ".gitignore").write_text("secrets.py\n")
        (tmp_path / "secrets.py").write_text("x = 1\n")
        (tmp_path / "main.py").write_text("x = 1\n")
        (tmp_path / "lib").mkdir()
        (tmp_path / "lib" / "helper.py").write_text("y = 1\n")
        (tmp_path / "lib" / "__init__.py").write_text("")
        (tmp_path / "__pycache__").mkdir()
        (tmp_path / "__pycache__" / "x.pyc").write_text("")
        files = sorted(p.name for p in iter_python_files(tmp_path))
        # __init__.py, main.py, helper.py — not secrets, not .pyc
        assert "main.py" in files
        assert "helper.py" in files
        assert "__init__.py" in files
        assert "secrets.py" not in files


class TestNoIgnoreFiles:
    def test_works_without_gitignore(self, tmp_path: Path):
        from ctxpack.core.code.exclusion import load_exclusion_rules
        # No .gitignore in tmp_path
        rules = load_exclusion_rules(tmp_path)
        assert rules.gitignore_patterns == []
        assert rules.ctxpackignore_patterns == []
